// flow-typed signature: 3e1687d1db1c61cee5c13955f7f9d176
// flow-typed version: <<STUB>>/cssrecipes-defaults_v^0.5.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cssrecipes-defaults'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cssrecipes-defaults' {
  declare module.exports: any;
}
