// flow-typed signature: 5aa627dbeac3e32240cb4e74ffecbdbb
// flow-typed version: <<STUB>>/ink-docstrap_v^1.3.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ink-docstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ink-docstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ink-docstrap/_plugins/BackboneUnderscoreClassLends' {
  declare module.exports: any;
}

declare module 'ink-docstrap/fixtures/base/chains' {
  declare module.exports: any;
}

declare module 'ink-docstrap/fixtures/base/index' {
  declare module.exports: any;
}

declare module 'ink-docstrap/fixtures/documents/binder' {
  declare module.exports: any;
}

declare module 'ink-docstrap/fixtures/documents/collector' {
  declare module.exports: any;
}

declare module 'ink-docstrap/fixtures/documents/model' {
  declare module.exports: any;
}

declare module 'ink-docstrap/fixtures/documents/probe' {
  declare module.exports: any;
}

declare module 'ink-docstrap/fixtures/documents/schema' {
  declare module.exports: any;
}

declare module 'ink-docstrap/fixtures/mixins/bussable' {
  declare module.exports: any;
}

declare module 'ink-docstrap/fixtures/mixins/signalable' {
  declare module.exports: any;
}

declare module 'ink-docstrap/fixtures/strings/format' {
  declare module.exports: any;
}

declare module 'ink-docstrap/fixtures/utils/logger' {
  declare module.exports: any;
}

declare module 'ink-docstrap/Gruntfile' {
  declare module.exports: any;
}

declare module 'ink-docstrap/template/publish' {
  declare module.exports: any;
}

declare module 'ink-docstrap/template/static/scripts/docstrap.lib' {
  declare module.exports: any;
}

declare module 'ink-docstrap/template/static/scripts/fulltext-search-ui' {
  declare module.exports: any;
}

declare module 'ink-docstrap/template/static/scripts/fulltext-search' {
  declare module.exports: any;
}

declare module 'ink-docstrap/template/static/scripts/lunr.min' {
  declare module.exports: any;
}

declare module 'ink-docstrap/template/static/scripts/prettify/jquery.min' {
  declare module.exports: any;
}

declare module 'ink-docstrap/template/static/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'ink-docstrap/template/static/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'ink-docstrap/template/static/scripts/sunlight' {
  declare module.exports: any;
}

declare module 'ink-docstrap/template/static/scripts/toc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ink-docstrap/_plugins/BackboneUnderscoreClassLends.js' {
  declare module.exports: $Exports<'ink-docstrap/_plugins/BackboneUnderscoreClassLends'>;
}
declare module 'ink-docstrap/fixtures/base/chains.js' {
  declare module.exports: $Exports<'ink-docstrap/fixtures/base/chains'>;
}
declare module 'ink-docstrap/fixtures/base/index.js' {
  declare module.exports: $Exports<'ink-docstrap/fixtures/base/index'>;
}
declare module 'ink-docstrap/fixtures/documents/binder.js' {
  declare module.exports: $Exports<'ink-docstrap/fixtures/documents/binder'>;
}
declare module 'ink-docstrap/fixtures/documents/collector.js' {
  declare module.exports: $Exports<'ink-docstrap/fixtures/documents/collector'>;
}
declare module 'ink-docstrap/fixtures/documents/model.js' {
  declare module.exports: $Exports<'ink-docstrap/fixtures/documents/model'>;
}
declare module 'ink-docstrap/fixtures/documents/probe.js' {
  declare module.exports: $Exports<'ink-docstrap/fixtures/documents/probe'>;
}
declare module 'ink-docstrap/fixtures/documents/schema.js' {
  declare module.exports: $Exports<'ink-docstrap/fixtures/documents/schema'>;
}
declare module 'ink-docstrap/fixtures/mixins/bussable.js' {
  declare module.exports: $Exports<'ink-docstrap/fixtures/mixins/bussable'>;
}
declare module 'ink-docstrap/fixtures/mixins/signalable.js' {
  declare module.exports: $Exports<'ink-docstrap/fixtures/mixins/signalable'>;
}
declare module 'ink-docstrap/fixtures/strings/format.js' {
  declare module.exports: $Exports<'ink-docstrap/fixtures/strings/format'>;
}
declare module 'ink-docstrap/fixtures/utils/logger.js' {
  declare module.exports: $Exports<'ink-docstrap/fixtures/utils/logger'>;
}
declare module 'ink-docstrap/Gruntfile.js' {
  declare module.exports: $Exports<'ink-docstrap/Gruntfile'>;
}
declare module 'ink-docstrap/template/publish.js' {
  declare module.exports: $Exports<'ink-docstrap/template/publish'>;
}
declare module 'ink-docstrap/template/static/scripts/docstrap.lib.js' {
  declare module.exports: $Exports<'ink-docstrap/template/static/scripts/docstrap.lib'>;
}
declare module 'ink-docstrap/template/static/scripts/fulltext-search-ui.js' {
  declare module.exports: $Exports<'ink-docstrap/template/static/scripts/fulltext-search-ui'>;
}
declare module 'ink-docstrap/template/static/scripts/fulltext-search.js' {
  declare module.exports: $Exports<'ink-docstrap/template/static/scripts/fulltext-search'>;
}
declare module 'ink-docstrap/template/static/scripts/lunr.min.js' {
  declare module.exports: $Exports<'ink-docstrap/template/static/scripts/lunr.min'>;
}
declare module 'ink-docstrap/template/static/scripts/prettify/jquery.min.js' {
  declare module.exports: $Exports<'ink-docstrap/template/static/scripts/prettify/jquery.min'>;
}
declare module 'ink-docstrap/template/static/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'ink-docstrap/template/static/scripts/prettify/lang-css'>;
}
declare module 'ink-docstrap/template/static/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'ink-docstrap/template/static/scripts/prettify/prettify'>;
}
declare module 'ink-docstrap/template/static/scripts/sunlight.js' {
  declare module.exports: $Exports<'ink-docstrap/template/static/scripts/sunlight'>;
}
declare module 'ink-docstrap/template/static/scripts/toc.js' {
  declare module.exports: $Exports<'ink-docstrap/template/static/scripts/toc'>;
}
