// flow-typed signature: f8adf30e13ffded72b6162fd24639eb6
// flow-typed version: <<STUB>>/mobx-react-router_v^4.0.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-react-router/__test__/store.spec' {
  declare module.exports: any;
}

declare module 'mobx-react-router/__test__/sync.spec' {
  declare module.exports: any;
}

declare module 'mobx-react-router/__test__/types.spec' {
  declare module.exports: any;
}

declare module 'mobx-react-router/dist/mobx-react-router' {
  declare module.exports: any;
}

declare module 'mobx-react-router/dist/mobx-react-router.min' {
  declare module.exports: any;
}

declare module 'mobx-react-router/src/store' {
  declare module.exports: any;
}

declare module 'mobx-react-router/src/sync' {
  declare module.exports: any;
}

declare module 'mobx-react-router/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-react-router/__test__/store.spec.js' {
  declare module.exports: $Exports<'mobx-react-router/__test__/store.spec'>;
}
declare module 'mobx-react-router/__test__/sync.spec.js' {
  declare module.exports: $Exports<'mobx-react-router/__test__/sync.spec'>;
}
declare module 'mobx-react-router/__test__/types.spec.js' {
  declare module.exports: $Exports<'mobx-react-router/__test__/types.spec'>;
}
declare module 'mobx-react-router/dist/mobx-react-router.js' {
  declare module.exports: $Exports<'mobx-react-router/dist/mobx-react-router'>;
}
declare module 'mobx-react-router/dist/mobx-react-router.min.js' {
  declare module.exports: $Exports<'mobx-react-router/dist/mobx-react-router.min'>;
}
declare module 'mobx-react-router/index' {
  declare module.exports: $Exports<'mobx-react-router'>;
}
declare module 'mobx-react-router/index.js' {
  declare module.exports: $Exports<'mobx-react-router'>;
}
declare module 'mobx-react-router/src/store.js' {
  declare module.exports: $Exports<'mobx-react-router/src/store'>;
}
declare module 'mobx-react-router/src/sync.js' {
  declare module.exports: $Exports<'mobx-react-router/src/sync'>;
}
declare module 'mobx-react-router/webpack.config.js' {
  declare module.exports: $Exports<'mobx-react-router/webpack.config'>;
}
