// flow-typed signature: 3b1957cd26b17962363f7c6a0a6a1d6a
// flow-typed version: <<STUB>>/react-addons-pure-render-mixin_v^15.3.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-addons-pure-render-mixin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-addons-pure-render-mixin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-addons-pure-render-mixin/index' {
  declare module.exports: $Exports<'react-addons-pure-render-mixin'>;
}
declare module 'react-addons-pure-render-mixin/index.js' {
  declare module.exports: $Exports<'react-addons-pure-render-mixin'>;
}
